import "server-only";
import { PDFDocument, StandardFonts, rgb, type PDFFont } from "pdf-lib";
import { sanitizeCell } from "./sanitize";

export interface ReportMeta {
  title: string;
  generatedBy: string;
  generatedAt: Date;
  filters?: Record<string, string>;
}

/**
 * Generate a PDF report buffer using pdf-lib.
 *
 * Layout: A4 landscape, header block, data table, page footer.
 * All string values are passed through sanitizeCell() before rendering.
 *
 * Security: server-only — never runs client-side.
 */
export async function generatePDF(
  meta: ReportMeta,
  headers: string[],
  rows: unknown[][]
): Promise<Buffer> {
  const doc = await PDFDocument.create();

  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);

  // A4 landscape: 841.89 x 595.28 pt
  const PAGE_W = 841.89;
  const PAGE_H = 595.28;
  const MARGIN = 36;
  const CONTENT_W = PAGE_W - MARGIN * 2;

  // Typography constants
  const TITLE_SIZE = 13;
  const META_SIZE = 8;
  const HEADER_SIZE = 8;
  const ROW_SIZE = 8;
  const ROW_HEIGHT = 14;
  const HEADER_HEIGHT = 16;

  // Colors
  const HEADER_BG = rgb(0.231, 0.392, 0.627); // NEA blue
  const HEADER_FG = rgb(1, 1, 1);
  const ALT_ROW_BG = rgb(0.961, 0.969, 0.98);
  const BORDER_COLOR = rgb(0.82, 0.835, 0.855);
  const TITLE_COLOR = rgb(0.1, 0.1, 0.1);
  const META_COLOR = rgb(0.45, 0.45, 0.45);
  const FOOTER_COLOR = rgb(0.55, 0.55, 0.55);

  // Calculate equal column widths
  const COL_W = CONTENT_W / Math.max(headers.length, 1);

  // How many rows fit per page (after header block + column headers)
  const HEADER_BLOCK_H = 52; // title + meta lines + gap
  const FOOTER_H = 18;
  const usable = PAGE_H - MARGIN * 2 - HEADER_BLOCK_H - HEADER_HEIGHT - FOOTER_H;
  const ROWS_PER_PAGE = Math.floor(usable / ROW_HEIGHT);

  // Split rows into pages
  const totalPages = Math.max(1, Math.ceil(rows.length / ROWS_PER_PAGE));

  for (let pageIdx = 0; pageIdx < totalPages; pageIdx++) {
    const page = doc.addPage([PAGE_W, PAGE_H]);
    const pageRows = rows.slice(pageIdx * ROWS_PER_PAGE, (pageIdx + 1) * ROWS_PER_PAGE);

    // ── Header block (first page only shows full title; subsequent show compact) ──
    let y = PAGE_H - MARGIN;

    if (pageIdx === 0) {
      // Title
      page.drawText(sanitizeCell(meta.title), {
        x: MARGIN,
        y,
        size: TITLE_SIZE,
        font: helveticaBold,
        color: TITLE_COLOR,
      });
      y -= TITLE_SIZE + 4;

      // Meta line 1: generated by + at
      const phtTime = meta.generatedAt.toLocaleString("en-PH", {
        timeZone: "Asia/Manila",
        dateStyle: "medium",
        timeStyle: "short",
      });
      page.drawText(
        `Generated by: ${sanitizeCell(meta.generatedBy)}   Date/Time (PHT): ${phtTime}`,
        { x: MARGIN, y, size: META_SIZE, font: helvetica, color: META_COLOR }
      );
      y -= META_SIZE + 3;

      // Meta line 2: active filters
      if (meta.filters && Object.keys(meta.filters).length > 0) {
        const filterStr = Object.entries(meta.filters)
          .filter(([, v]) => v)
          .map(([k, v]) => `${k}: ${sanitizeCell(v)}`)
          .join("   ");
        page.drawText(`Filters: ${filterStr}`, {
          x: MARGIN, y, size: META_SIZE, font: helvetica, color: META_COLOR,
        });
        y -= META_SIZE + 3;
      }

      y -= 6; // gap before table
    } else {
      // Compact header for continuation pages
      page.drawText(`${sanitizeCell(meta.title)} (continued)`, {
        x: MARGIN, y, size: META_SIZE + 1, font: helveticaBold, color: TITLE_COLOR,
      });
      y -= META_SIZE + 1 + 8;
    }

    // ── Column header row ──────────────────────────────────────────────────
    page.drawRectangle({
      x: MARGIN, y: y - HEADER_HEIGHT,
      width: CONTENT_W, height: HEADER_HEIGHT,
      color: HEADER_BG,
    });

    for (let ci = 0; ci < headers.length; ci++) {
      const cellX = MARGIN + ci * COL_W + 3;
      const maxWidth = COL_W - 6;
      const label = truncateText(sanitizeCell(headers[ci]), maxWidth, HEADER_SIZE, helveticaBold);
      page.drawText(label, {
        x: cellX,
        y: y - HEADER_HEIGHT + 4,
        size: HEADER_SIZE,
        font: helveticaBold,
        color: HEADER_FG,
        maxWidth,
      });
    }

    // Column separator lines in header
    for (let ci = 1; ci < headers.length; ci++) {
      page.drawLine({
        start: { x: MARGIN + ci * COL_W, y: y },
        end: { x: MARGIN + ci * COL_W, y: y - HEADER_HEIGHT },
        thickness: 0.3,
        color: rgb(1, 1, 1),
        opacity: 0.4,
      });
    }

    y -= HEADER_HEIGHT;

    // ── Data rows ──────────────────────────────────────────────────────────
    for (let ri = 0; ri < pageRows.length; ri++) {
      const rowY = y - (ri + 1) * ROW_HEIGHT;
      const isAlt = ri % 2 === 1;

      // Alternating row background
      if (isAlt) {
        page.drawRectangle({
          x: MARGIN, y: rowY,
          width: CONTENT_W, height: ROW_HEIGHT,
          color: ALT_ROW_BG,
        });
      }

      // Row bottom border
      page.drawLine({
        start: { x: MARGIN, y: rowY },
        end: { x: MARGIN + CONTENT_W, y: rowY },
        thickness: 0.2,
        color: BORDER_COLOR,
      });

      // Cell values
      for (let ci = 0; ci < headers.length; ci++) {
        const cellValue = sanitizeCell(pageRows[ri][ci]);
        const cellX = MARGIN + ci * COL_W + 3;
        const maxWidth = COL_W - 6;
        const display = truncateText(cellValue, maxWidth, ROW_SIZE, helvetica);
        page.drawText(display, {
          x: cellX,
          y: rowY + 3,
          size: ROW_SIZE,
          font: helvetica,
          color: TITLE_COLOR,
          maxWidth,
        });

        // Column separator
        if (ci > 0) {
          page.drawLine({
            start: { x: MARGIN + ci * COL_W, y: rowY + ROW_HEIGHT },
            end: { x: MARGIN + ci * COL_W, y: rowY },
            thickness: 0.2,
            color: BORDER_COLOR,
          });
        }
      }
    }

    // Outer table border
    const tableHeight = (pageRows.length + 1) * ROW_HEIGHT + (pageIdx === 0 ? 0 : 0);
    page.drawRectangle({
      x: MARGIN, y: y - pageRows.length * ROW_HEIGHT,
      width: CONTENT_W, height: HEADER_HEIGHT + pageRows.length * ROW_HEIGHT,
      borderColor: BORDER_COLOR,
      borderWidth: 0.5,
      opacity: 0,
      borderOpacity: 1,
    });
    void tableHeight; // suppress unused warning

    // ── Footer ──────────────────────────────────────────────────────────────
    const footerY = MARGIN - 6;
    page.drawText("IMIS — Confidential — Philippine Electric Cooperative", {
      x: MARGIN, y: footerY,
      size: 7, font: helvetica, color: FOOTER_COLOR,
    });
    page.drawText(`Page ${pageIdx + 1} of ${totalPages}`, {
      x: PAGE_W - MARGIN - 50, y: footerY,
      size: 7, font: helvetica, color: FOOTER_COLOR,
    });

    // Footer separator
    page.drawLine({
      start: { x: MARGIN, y: footerY + 9 },
      end: { x: PAGE_W - MARGIN, y: footerY + 9 },
      thickness: 0.3,
      color: BORDER_COLOR,
    });
  }

  const bytes = await doc.save();
  return Buffer.from(bytes);
}

/**
 * Truncate text to fit within a given pixel width.
 * pdf-lib doesn't auto-wrap; we truncate manually and add ellipsis.
 */
function truncateText(text: string, maxPx: number, fontSize: number, font: PDFFont): string {
  const width = font.widthOfTextAtSize(text, fontSize);
  if (width <= maxPx) return text;

  const ellipsis = "…";
  const ellipsisW = font.widthOfTextAtSize(ellipsis, fontSize);
  let truncated = text;
  while (truncated.length > 0 && font.widthOfTextAtSize(truncated, fontSize) + ellipsisW > maxPx) {
    truncated = truncated.slice(0, -1);
  }
  return truncated + ellipsis;
}
